version: 0.2
env:
  variables:
    ECR_REPO_NAME: microservicio-solicitudes-interconsulta
phases:
  pre_build:
    commands:
      # Docker Hub login
      - echo "dckr_pat_qDaLrCwn88VEoiPa7N9GrIaDIhw" | docker login -u bitius060400 --password-stdin 
      - mvn clean package -Dmaven.test.skip=true
      # ECR login
      - ECR_MAIN_URI="583863894994.dkr.ecr.us-east-1.amazonaws.com"
      - aws ecr get-login-password --region us-east-1 | docker login -u AWS --password-stdin ${ECR_MAIN_URI}

      - ECR_IMAGE_URI="${ECR_MAIN_URI}/${ECR_REPO_NAME}:latest"
  build:
    commands:
      - docker build -t microservicio-solicitudes-interconsulta:latest .
  post_build:
    commands:
      - docker tag microservicio-solicitudes-interconsulta:latest ${ECR_IMAGE_URI}
      - docker push ${ECR_IMAGE_URI}
      - printf '[{"name":"microservicio-solicitudes-interconsulta","imageUri":"%s"}]' ${ECR_IMAGE_URI} > imagedefinitions.json
      
artifacts:
  files:
    - imagedefinitions.json