# spring:
#     datasource:
#         url: jdbc:mysql://${IP:localhost}:${PORT:3306}/${DATABASE:gestion-consultas-externas}
#         username: ${USER:root}
#         password: ${PASSWORD:admin}
#         show-sql: true
# server:
#   port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: ${HOSTNAME:localhost}